In [45]:
import numpy as np
def sigmoid(x):
    return (1/(1+np.exp(-x)))

def zeros():
    return np.zeros(10)

def size(l):
    L = np.array(l)
    return L.size

def Q6():
    return np.append(np.append(np.zeros(3),np.ones(1)),np.zeros(6))

def Q7():
    return np.arange(10,46)

def Q8(arr):
    return arr[::-1]

def Q9():
    return np.reshape(np.arange(0,9),(3,3))

#retourne les incides comportante un chiffre non zero
def Q10(l):
    return np.nonzero(l)

def Q11():
    return np.eye(3)

def Q12():
    return np.random.random((3,3,3))

def Q13():
    return np.max(np.random.random((10,10))) , np.min(np.random.random((10,10)))

def Q14():
    return np.mean(np.random.random(30))

def Q15():
    l = np.ones((10,10))
    l[1:-1, 1:-1] = 0
    return l

def Q16():
    l = np.ones((10,10))
    arr = np.pad(l, pad_width=1, mode='constant', constant_values=0)
    return arr

def Q17():
    

In [8]:
Q10([1,2,0,3,0])

(array([0, 1, 3], dtype=int64),)

In [51]:
np.nan in set([np.nan])

True

In [86]:
a = np.reshape(np.arange(0,25),(5,5))
l = np.diag([1,2,3,4],k=-1)
l+a-np.diag(np.diag(a,k=-1),k=-1)

        

array([[ 0,  1,  2,  3,  4],
       [ 1,  6,  7,  8,  9],
       [10,  2, 12, 13, 14],
       [15, 16,  3, 18, 19],
       [20, 21, 22,  4, 24]])

In [147]:
import numpy as np

#1.1
zero = np.zeros(6)
#1.2
one = np.ones(6)
#1.3
squarMat = np.arange(0,25).reshape((5,5))
squarMat
#1.4
Mat = np.arange(0,25).reshape((5,5))
np.diag(Mat, k=0)
#1.5
np.diag([1,1,1,1,1], k=0)
    #or
np.eye(5)
#1.6
l = np.random.rand(5, 5)
m = np.tril(l) + np.tril(l, -1).T
m
        


array([[0.53550215, 0.01589029, 0.31004212, 0.27293439, 0.92850419],
       [0.01589029, 0.48130698, 0.24501851, 0.73682189, 0.49784691],
       [0.31004212, 0.24501851, 0.67986654, 0.00315851, 0.08940427],
       [0.27293439, 0.73682189, 0.00315851, 0.68511607, 0.29296073],
       [0.92850419, 0.49784691, 0.08940427, 0.29296073, 0.87984888]])

array([[0.9596288 , 0.9596288 , 0.9596288 ],
       [0.1638728 , 0.1638728 , 0.1638728 ],
       [0.04084499, 0.04084499, 0.04084499]])

In [145]:
a = np.random.rand(5, 5)
m = np.tril(a) + np.tril(a, -1).T
m

array([[0.71305386, 0.7721271 , 0.46128454, 0.18529509, 0.95107946],
       [0.7721271 , 0.36932367, 0.06128681, 0.38758963, 0.4446897 ],
       [0.46128454, 0.06128681, 0.50716881, 0.8046428 , 0.69026569],
       [0.18529509, 0.38758963, 0.8046428 , 0.82800996, 0.9039783 ],
       [0.95107946, 0.4446897 , 0.69026569, 0.9039783 , 0.3489062 ]])

In [146]:
m == m.transpose()

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [152]:
#2.1
p = np.array([1000000,800000,500000])
n = np.array([3,4,5])
#2.2
np.multiply(p,n)



array([3000000, 3200000, 2500000])

In [161]:
from sklearn.datasets import load_digits
X=load_digits().data

X[1].shape

(64,)

In [169]:
def similarity(a,b):
    dot = np.dot(a, b)
    norma = np.linalg.norm(a)
    normb = np.linalg.norm(b)
    cos = dot / (norma * normb)
    return cos


In [171]:
a = np.ones((1797,1797))
for i in range(X.shape[0]):
    for j in range(X.shape[0]):
        a[i][j] = similarity(X[i],X[j])

a

array([[1.        , 0.51910234, 0.61684198, ..., 0.71121668, 0.82580797,
        0.74430965],
       [0.51910234, 1.        , 0.79859118, ..., 0.84372046, 0.72334144,
        0.72538603],
       [0.61684198, 0.79859118, 1.        , ..., 0.84727621, 0.70383842,
        0.7942196 ],
       ...,
       [0.71121668, 0.84372046, 0.84727621, ..., 1.        , 0.79544008,
        0.91695754],
       [0.82580797, 0.72334144, 0.70383842, ..., 0.79544008, 1.        ,
        0.83395856],
       [0.74430965, 0.72538603, 0.7942196 , ..., 0.91695754, 0.83395856,
        1.        ]])

In [195]:
from sklearn.datasets import load_boston
boston=load_boston()
X=boston.data
y=boston.target
A=X[:4, [0,4,5,6]] # ‘CRIM’,’NOX’,’RM’,’AGE’
b=y[:4]


In [199]:
All = A.sum(axis=1)


In [201]:
result = b/All
result

array([0.33186153, 0.25169747, 0.50449766, 0.62677841])

In [204]:
from sklearn.datasets import load_boston
boston=load_boston()
X=boston.data
y=boston.target

In [205]:
All = X.sum(axis=1)
result = y/All
print(result)


[0.02959677 0.02820969 0.04692497 0.04752415 0.05055539 0.04003403
 0.02731443 0.03091804 0.01873769 0.02211638 0.01719567 0.02204038
 0.02683194 0.02491073 0.02201647 0.02450051 0.02981047 0.02096235
 0.0293599  0.02212343 0.0160569  0.02313866 0.0176878  0.01674375
 0.01821405 0.01835705 0.01990802 0.01935667 0.02170987 0.02523725
 0.0153266  0.01721989 0.01901152 0.01590891 0.01881018 0.02380963
 0.02599613 0.02739035 0.03278439 0.0392131  0.04488534 0.03987849
 0.03781372 0.03623033 0.02977066 0.0270641  0.02790635 0.02155154
 0.01809521 0.02592656 0.02597384 0.02661466 0.03436245 0.0320341
 0.01808558 0.04543578 0.02831234 0.03805688 0.02975213 0.02424047
 0.02253396 0.01902137 0.02682764 0.03103152 0.04495714 0.02691327
 0.02175985 0.02666593 0.02056989 0.02493795 0.03234146 0.02873601
 0.0301948  0.03153381 0.02824427 0.02423499 0.02208652 0.02341513
 0.02358938 0.0228813  0.035799   0.02916055 0.03171983 0.02896024
 0.03233321 0.03597054 0.03049264 0.02984797 0.02976475 0.03731

In [207]:
import numpy as np

a = np.array([4,5,2,2])
b = np.array([4,0,2,0])
c = np.array([2,2,0,1])

distab = np.linalg.norm(a-b)
distac = np.linalg.norm(a-c)
distcb = np.linalg.norm(c-b)
np.min(np.array([distab,distac,distcb]))




3.605551275463989

In [208]:
np.linalg.norm(a-b)


5.385164807134504

In [210]:
np.linalg.norm(b-a)

5.385164807134504

In [212]:
# import required libraries
def cosin(A,B):
return cosine = np.dot(A,B)/(norm(A)*norm(B))


A: [2 1 2 3 2 9]
B: [3 4 2 4 5 5]
Cosine Similarity: 0.8188504723485274


In [229]:
a = np.array([4,5,2,2])
b = np.array([4,0,2,0])
c = np.array([2,2,0,1])

distab = np.linalg.norm(a-b)
distac = np.linalg.norm(a-c)
distcb = np.linalg.norm(c-b)
l = np.array([distab,distac,distcb])
closest = np.min(l)
farthest = np.max(l)
dico = {'a and b':distab, 'a and c':distac, 'b and c': distcb}

for key in dico:
    if( dico[key] == closest):
        print('closest users', key)
    elif(dico[key] == farthest):
        print('farthest users', key)


farthest users a and b
closest users b and c


In [230]:
np.linalg.norm(A-B)

6.0

In [235]:
a = np.array([4,5,2,2])
b = np.array([4,0,2,0])
c = np.array([2,2,0,1])
cosine1 = np.dot(a,b)/(norm(a)*norm(b))

cosine2 = np.dot(a,c)/(norm(a)*norm(c))

cosine3 = np.dot(c,b)/(norm(c)*norm(b))

cosine1 = 1 - np.dot(a,b)/(norm(a)*norm(b))

cosine2 = 1 - np.dot(a,c)/(norm(a)*norm(c))

cosine3 = 1 - np.dot(c,b)/(norm(c)*norm(b))

print("the farthest are b & c by a distance of : ",max(cosine1,cosine2,cosine3))
print("the closest are a & c by a distance of : ",min(cosine1,cosine2,cosine3))

Cosine distance a & b : 0.18114952765147263
Cosine distance of a & c: 0.18114952765147263
Cosine distance of b & c: 0.18114952765147263
Cosine distance a & b : 0.36112343500006017
Cosine distance of a & c: 0.04761904761904767
Cosine distance of b & c: 0.40371520600005606
the farthest are b & c by a distance of :  0.40371520600005606
the closest are a & c by a distance of :  0.04761904761904767


In [246]:
np.round(np.log(2), 2)

2.4849066497880004

In [5]:
import numpy as np
np.around(np.log(4),2)

1.39

In [22]:
Mylist = [1,2,3,4]
Mylist.insert(int(len(Mylist)/2),'Game')

In [26]:
del Mylist[2]

[1, 2, 3, 4]

In [27]:
newT = tuple('Fayçal')
newT

('F', 'a', 'y', 'ç', 'a', 'l')

In [30]:
Dict = {"Name" : "Fayçal","Num" : "0541127142","@Mail" : "elmoubarek.faycal@gmail.com",}
Dict['Name']

'Fayçal'

In [31]:
pairs = {1: "apple", "orange": [2, 3, 4],  True: False, None: "True"}  
print(pairs)

{1: False, 'orange': [2, 3, 4], None: 'True'}


In [34]:
Dict.items()

dict_items([('Name', 'Fayçal'), ('Num', '0541127142'), ('@Mail', 'elmoubarek.faycal@gmail.com')])

In [41]:
#using lambda

function = lambda x : x.split('/')
Date = '24/11/1959'
print(function(Date))
#using map and lambda



['24', '11', '1995']


In [49]:
class Player:
    
    def __init__(self, name, health, power):
        self.name = name
        self.health = health
        self.power = power
    
    def show(self):
        print("Player Name = ",self.name,"\n"+
              "Health = ",self.health,"\n"+
              "Power = ",self.power)
    
    def attack(self, player):
        player.health = player.health - (self.power/2)
        print(" Dammage",(self.power/2),"\n",player.name+ "'s Health =",player.health)

Player1 =Player('Fayçal',100, 35)
Player2 =Player('Nesrine',100, 15)
Players = [Player1,Player2]

import random
game = True
i=0
while(game):
    random.shuffle(Players)
    print(Players[0].name + ' Attack !!!')
    Players[0].attack(Players[1])
    print('\n \n \n')
    if(Players[0].health <0):
        print('',Players[0].name,'is dead.\n',Players[1].name,'Wins !!!')
        game=False
    elif(Players[1].health <0):
        print('',Players[1].name,'is dead.\n',Players[0].name,'Wins !!!')
        game=False

Nesrine Attack !!!
 Dammage 7.5 
 Fayçal's Health = 92.5

 
 

Nesrine Attack !!!
 Dammage 7.5 
 Fayçal's Health = 85.0

 
 

Fayçal Attack !!!
 Dammage 17.5 
 Nesrine's Health = 82.5

 
 

Fayçal Attack !!!
 Dammage 17.5 
 Nesrine's Health = 65.0

 
 

Fayçal Attack !!!
 Dammage 17.5 
 Nesrine's Health = 47.5

 
 

Nesrine Attack !!!
 Dammage 7.5 
 Fayçal's Health = 77.5

 
 

Nesrine Attack !!!
 Dammage 7.5 
 Fayçal's Health = 70.0

 
 

Fayçal Attack !!!
 Dammage 17.5 
 Nesrine's Health = 30.0

 
 

Nesrine Attack !!!
 Dammage 7.5 
 Fayçal's Health = 62.5

 
 

Fayçal Attack !!!
 Dammage 17.5 
 Nesrine's Health = 12.5

 
 

Fayçal Attack !!!
 Dammage 17.5 
 Nesrine's Health = -5.0

 
 

 Nesrine is dead.
 Fayçal Wins !!!
